version: '3'

services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c "python manage.py makemigrations --noinput"
    command: bash -c "python manage.py migrate --noinput"
    command: bash -c "python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app

    depends_on:
      - db
    environment:
      - DB_PG_NAME=postgres
      - DB_PG_USER=postgres
      - DB_PG_PASSWORD=postgres
      - DB_PG_HOST=db
      - DB_PG_PORT=5432
    ports:
      - "8000:8000"
